version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  backend:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3020 -b '0.0.0.0'"
    volumes:
      - .:/backend
    ports:
      - "3307:3306"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - .:/frontend/
    command: sh -c "cd frontend && PORT=3001 yarn start"
    ports:
      - "3001:3001"
volumes:
  mysql-data: